// <auto-generated />
using System;
using Coredet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Coredet.Data.Migrations
{
    [DbContext(typeof(CoredetContext))]
    partial class CoredetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Coredet.Core.Entities.Basket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Basket");
                });

            modelBuilder.Entity("Coredet.Core.Entities.BasketProducts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BasketId")
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.HasIndex("ProductId");

                    b.ToTable("BasketProducts");
                });

            modelBuilder.Entity("Coredet.Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a382002d-d515-4e40-99c6-f1069d151369"),
                            CreatedDate = new DateTime(2021, 11, 8, 20, 41, 12, 156, DateTimeKind.Utc).AddTicks(1950),
                            ImageUrl = "https://cdn.britannica.com/96/1296-050-4A65097D/gelding-bay-coat.jpg",
                            IsDeleted = false,
                            Name = "Beygir At",
                            Price = 50m
                        },
                        new
                        {
                            Id = new Guid("c23cab66-ff72-477b-a628-e531e7849e3a"),
                            CreatedDate = new DateTime(2021, 11, 8, 20, 41, 12, 156, DateTimeKind.Utc).AddTicks(1979),
                            ImageUrl = "https://cdn.britannica.com/96/1296-050-4A65097D/gelding-bay-coat.jpg",
                            IsDeleted = false,
                            Name = "Safkan Arap At",
                            Price = 50m
                        },
                        new
                        {
                            Id = new Guid("69cf9987-323d-4015-af30-dce2ca307840"),
                            CreatedDate = new DateTime(2021, 11, 8, 20, 41, 12, 156, DateTimeKind.Utc).AddTicks(1982),
                            ImageUrl = "https://cdn.britannica.com/96/1296-050-4A65097D/gelding-bay-coat.jpg",
                            IsDeleted = false,
                            Name = "Alaca Kısrak At",
                            Price = 50m
                        },
                        new
                        {
                            Id = new Guid("0d1275ed-ca9b-470c-a028-943dc17518f1"),
                            CreatedDate = new DateTime(2021, 11, 8, 20, 41, 12, 156, DateTimeKind.Utc).AddTicks(1984),
                            ImageUrl = "https://media.gq.com/photos/56e71c0b14cbe0637b261d7f/4:3/w_2260,h_1695,c_limit/horseinsuit2.jpg",
                            IsDeleted = false,
                            Name = "Rahvan At",
                            Price = 50m
                        },
                        new
                        {
                            Id = new Guid("a52d8454-c582-4be3-986f-e28a7b07a0c4"),
                            CreatedDate = new DateTime(2021, 11, 8, 20, 41, 12, 156, DateTimeKind.Utc).AddTicks(1987),
                            ImageUrl = "https://cdn.britannica.com/96/1296-050-4A65097D/gelding-bay-coat.jpg",
                            IsDeleted = false,
                            Name = "Doru At",
                            Price = 50m
                        },
                        new
                        {
                            Id = new Guid("5bf9b37e-ccc8-4d71-a2b6-f55c7110a61c"),
                            CreatedDate = new DateTime(2021, 11, 8, 20, 41, 12, 156, DateTimeKind.Utc).AddTicks(1989),
                            ImageUrl = "http://cdn.shopify.com/s/files/1/0420/2528/7847/products/Horse-Rug-Liner-Black-Test.jpg?v=1631720831",
                            IsDeleted = false,
                            Name = "Şişme Mont At",
                            Price = 50m
                        },
                        new
                        {
                            Id = new Guid("1e18b95f-08f9-4bb6-8151-9290a3d8c3d3"),
                            CreatedDate = new DateTime(2021, 11, 8, 20, 41, 12, 156, DateTimeKind.Utc).AddTicks(2003),
                            ImageUrl = "https://cdn.britannica.com/96/1296-050-4A65097D/gelding-bay-coat.jpg",
                            IsDeleted = false,
                            Name = "Binek At At",
                            Price = 50m
                        },
                        new
                        {
                            Id = new Guid("a9776e71-893f-4668-a9a0-68a92b1f5117"),
                            CreatedDate = new DateTime(2021, 11, 8, 20, 41, 12, 156, DateTimeKind.Utc).AddTicks(2005),
                            ImageUrl = "https://cdn.britannica.com/96/1296-050-4A65097D/gelding-bay-coat.jpg",
                            IsDeleted = false,
                            Name = "Tinker Güzeli At",
                            Price = 50m
                        },
                        new
                        {
                            Id = new Guid("86613a15-6a77-4735-b87b-32ea18f234c9"),
                            CreatedDate = new DateTime(2021, 11, 8, 20, 41, 12, 156, DateTimeKind.Utc).AddTicks(2007),
                            ImageUrl = "https://www.horze.eu/dw/image/v2/AATB_PRD/on/demandware.static/-/Sites-hz-master-catalog/default/dwa5525f47/Harryshorse/331637_BL.jpg?sw=1600&sh=1600&q=100",
                            IsDeleted = false,
                            Name = "Kör At",
                            Price = 50m
                        },
                        new
                        {
                            Id = new Guid("d49f30a3-217e-45ec-84e6-d6e8f4fe4a94"),
                            CreatedDate = new DateTime(2021, 11, 8, 20, 41, 12, 156, DateTimeKind.Utc).AddTicks(2009),
                            ImageUrl = "https://cdn.britannica.com/96/1296-050-4A65097D/gelding-bay-coat.jpg",
                            IsDeleted = false,
                            Name = "Midilli At",
                            Price = 50m
                        },
                        new
                        {
                            Id = new Guid("eab24f64-5aa7-4f11-9373-3a3c235cb89a"),
                            CreatedDate = new DateTime(2021, 11, 8, 20, 41, 12, 156, DateTimeKind.Utc).AddTicks(2081),
                            ImageUrl = "https://cdn.britannica.com/96/1296-050-4A65097D/gelding-bay-coat.jpg",
                            IsDeleted = false,
                            Name = "Beygir",
                            Price = 50m
                        });
                });

            modelBuilder.Entity("Coredet.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8867c3f7-e10d-46a2-8f23-026791cb7e01"),
                            CreatedDate = new DateTime(2021, 11, 8, 20, 41, 12, 153, DateTimeKind.Utc).AddTicks(6169),
                            IsDeleted = false,
                            Name = "ikbalkazanc",
                            Password = "123"
                        });
                });

            modelBuilder.Entity("Coredet.Core.Entities.BasketProducts", b =>
                {
                    b.HasOne("Coredet.Core.Entities.Basket", "Basket")
                        .WithMany()
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coredet.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
